spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8705

eureka:
  instance:
    instance-id: ${spring.application.name}:
                   ${spring.aplication.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka